mqtt:
  broker: "${MQTT_BROKER}"
  port: "${MQTT_PORT}" 
  username: "${MQTT_USER}"
  password: "${MQTT_PASSWORD}"
  topic: "topic/aoatest"

database:
  path: "192.168.77.108:/mnt/usbDisk3T/mysql_db/mysql/aoa.db"
  timeout: 10

visualization:
  refresh_interval: 5
  figure_size: [10, 6]

version: 0.1
release_date: 2024-05-25
changelog:
  - 初始版本发布
  - 实现蓝牙AOA数据解析基础功能
  - 集成MQTT消息订阅模块
 